=== skajel/xml-semestralniPrace/semestralniPrace.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns="urn:vse.cz:steo08_sem_prace" targetNamespace="urn:vse.cz:steo08_sem_prace"
    xmlns:s="urn:vse.cz:steo08_sem_prace">

    <xs:element name="uzivatele" type="uzivateleType">
        <xs:key name="idUzivateleKey">
            <xs:selector xpath="s:uzivatel/s:osobni_udaje"/>
            <xs:field xpath="@id_uzivatele"/>
        </xs:key>
        <xs:key name="idTrasyKey">
            <xs:selector xpath="s:uzivatel/s:jizdenky/s:jizdenka/s:trasa"/>
            <xs:field xpath="@id_trasy"/>
        </xs:key>
        <xs:key name="danovy_dokladKey">
            <xs:selector xpath="s:uzivatel/s:jizdenky/s:jizdenka/s:nakup/s:polozky/s:polozka"/>
            <xs:field xpath="@danovy_doklad"/>
        </xs:key>
    </xs:element>

    <xs:complexType name="uzivateleType">
        <xs:sequence>
            <xs:element name="uzivatel" maxOccurs="unbounded" type="uzivatelType"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="uzivatelType">
        <xs:sequence>
            <xs:element name="osobni_udaje" type="osobniUdajeType"/>
            <xs:element name="jizdenky" type="jizdenkyType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="osobniUdajeType">
        <xs:sequence>
            <xs:element name="jmeno" type="neprazdnyString"/>
            <xs:element name="prijmeni" type="neprazdnyString"/>
            <xs:element name="datum" type="datumType"/>
            <xs:element name="email" type="emailType"/>
            <xs:element name="telefon" type="telefonType"/>
            <xs:element name="sleva" type="slevaType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id_uzivatele" type="idUzivateleType" use="required"/>
    </xs:complexType>

    <xs:complexType name="jizdenkyType">
        <xs:sequence>
            <xs:element name="jizdenka" type="jizdenkaType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="jizdenkaType">
        <xs:sequence>
            <xs:element name="trasa" type="trasaType"/>
            <xs:element name="nakup" type="nakupType" minOccurs="0"/>
            <xs:element name="dotaznik" type="dotaznikType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dotaznikType">
        <xs:sequence>
            <xs:element name="hodnoceni" type="hodnoceniType"/>
            <xs:element name="komentar" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="hodnoceniType">
        <xs:sequence>
            <xs:element name="celkove" type="hodnoticiType"/>
            <xs:element name="personal" type="hodnoticiType"/>
            <xs:element name="cistota" type="hodnoticiType"/>
        </xs:sequence>
    </xs:complexType>


    <xs:simpleType name="hodnoticiType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="nakupType">
        <xs:sequence>
            <xs:element name="polozky" type="polozkyType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="polozkyType">
        <xs:sequence>
            <xs:element name="polozka" type="polozkaType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="polozkaType">
        <xs:sequence>
            <xs:element name="nazev" type="neprazdnyString"/>
            <xs:element name="cena" type="cenaType"/>
            <xs:element name="uhrazeno" type="uhrazenoType"/>
        </xs:sequence>
        <xs:attribute name="danovy_doklad" type="danovyDokladType" use="required"/>
    </xs:complexType>

    <xs:simpleType name="danovyDokladType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]{12})"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="trasaType">
        <xs:sequence>
            <xs:element name="informace" type="informaceType"/>
            <xs:element name="platba" type="platbaType"/>
        </xs:sequence>
        <xs:attribute name="id_trasy" type="idTrasyType" use="required"/>
    </xs:complexType>

    <xs:simpleType name="idTrasyType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]{5})-([0-9]{5})-([0-9]{5})"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="informaceType">
        <xs:sequence>
            <xs:element name="datum" type="datumType"/>
            <xs:element name="odkud" type="neprazdnyString"/>
            <xs:element name="kam" type="neprazdnyString"/>
            <xs:element name="vyjezd" type="xs:time"/>
            <xs:element name="prijezd" type="xs:time"/>
            <xs:element name="trida" type="tridaType"/>
            <xs:element name="sedadlo" type="sedadloType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sedadloType">
        <xs:sequence>
            <xs:element name="vuz" type="vuzType"/>
            <xs:element name="cislo" type="cisloType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="platbaType">
        <xs:sequence>
            <xs:element name="datum" type="datumType"/>
            <xs:element name="cena" type="cenaType"/>
            <xs:element name="uhrazeno" type="uhrazenoType"/>
        </xs:sequence>
    </xs:complexType>


    <xs:simpleType name="slevaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ISIC"/>
            <xs:enumeration value="ZTP"/>
            <xs:enumeration value="ITIC"/>
            <xs:enumeration value="interrail-1st"/>
            <xs:enumeration value="interrail-2nd"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="cenaType">
        <xs:simpleContent>
            <xs:extension base="xs:nonNegativeInteger">
                <xs:attribute name="mena" type="menaType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="datumType">
        <xs:simpleContent>
            <xs:extension base="xs:date">
                <xs:attribute name="oznaceni" type="oznaceniType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="oznaceniType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="nakup"/>
            <xs:enumeration value="narozeni"/>
            <xs:enumeration value="jizdenka"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idUzivateleType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]{4})-([0-9]{4})"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="uhrazenoType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="hotovost"/>
            <xs:enumeration value="karta"/>
            <xs:enumeration value="kredity"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"
            />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="telefonType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\+[0-9]{3})([0-9]{9})"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="vuzType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A"/>
            <xs:enumeration value="B"/>
            <xs:enumeration value="C"/>
            <xs:enumeration value="D"/>
            <xs:enumeration value="E"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tridaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="economy"/>
            <xs:enumeration value="economy+"/>
            <xs:enumeration value="business"/>
            <xs:enumeration value="premium"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cisloType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="220"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="neprazdnyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="menaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CZK"/>
            <xs:enumeration value="USD"/>
            <xs:enumeration value="EUR"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="pocetBoduType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== skajel/xml-semestralniPrace/semestralniPrace.xml
<?xml version="1.0" encoding="UTF-8"?>
<uzivatele xmlns="urn:vse.cz:steo08_sem_prace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:vse.cz:steo08_sem_prace semestralniPrace.xsd">
    <uzivatel>
        <osobni_udaje id_uzivatele="1562-1251">
            <jmeno>Ondřej</jmeno>
            <prijmeni>Štěpán</prijmeni>
            <datum oznaceni="narozeni">1999-06-28</datum>
            <email>steo08@vse.cz</email>
            <telefon>+420737194535</telefon>
            <sleva>ISIC</sleva>
        </osobni_udaje>
        <jizdenky>
            <jizdenka>
                <trasa id_trasy="20291-20918-01699">
                    <informace>
                        <datum oznaceni="jizdenka">2020-12-14</datum>
                        <odkud>Studénka</odkud>
                        <kam>Praha, hl.n.</kam>
                        <vyjezd>16:20:00</vyjezd>
                        <prijezd>19:27:00</prijezd>
                        <trida>economy</trida>
                        <sedadlo>
                            <vuz>D</vuz>
                            <cislo>178</cislo>
                        </sedadlo>
                    </informace>
                    <platba>
                        <datum oznaceni="nakup">2020-12-13</datum>
                        <cena mena="CZK">72</cena>
                        <uhrazeno>kredity</uhrazeno>
                    </platba>
                </trasa>
                <nakup>
                    <polozky>
                        <polozka danovy_doklad="113234900009">
                            <nazev>Bageta se šunkou a sýrem</nazev>
                            <cena mena="CZK">45</cena>
                            <uhrazeno>hotovost</uhrazeno>
                        </polozka>
                        <polozka danovy_doklad="108783490004">
                            <nazev>Sushi</nazev>
                            <cena mena="CZK">119</cena>
                            <uhrazeno>kredity</uhrazeno>
                        </polozka>
                    </polozky>
                </nakup>
                <dotaznik>
                    <hodnoceni>
                        <celkove>7</celkove>
                        <personal>9</personal>
                        <cistota>5</cistota>
                    </hodnoceni>
                    <komentar>Děkuji za příjemnou cestu.</komentar>
                </dotaznik>
            </jizdenka>
            <jizdenka>
                <trasa id_trasy="20264-46312-64032">
                    <informace>
                        <datum oznaceni="jizdenka">2020-12-12</datum>
                        <odkud>Praha, hl.n.</odkud>
                        <kam>Studénka</kam>
                        <vyjezd>12:08:00</vyjezd>
                        <prijezd>15:18:00</prijezd>
                        <trida>economy+</trida>
                        <sedadlo>
                            <vuz>D</vuz>
                            <cislo>164</cislo>
                        </sedadlo>
                    </informace>
                    <platba>
                        <datum oznaceni="nakup">2020-12-04</datum>
                        <cena mena="CZK">59</cena>
                        <uhrazeno>karta</uhrazeno>
                    </platba>
                </trasa>
            </jizdenka>
            <jizdenka>
                <trasa id_trasy="20251-73110-88364">
                    <informace>
                        <datum oznaceni="jizdenka">2020-08-01</datum>
                        <odkud>Praha, hl.n.</odkud>
                        <kam>Hranice na Moravě</kam>
                        <vyjezd>10:08:00</vyjezd>
                        <prijezd>13:04:00</prijezd>
                        <trida>economy</trida>
                        <sedadlo>
                            <vuz>A</vuz>
                            <cislo>56</cislo>
                        </sedadlo>
                    </informace>
                    <platba>
                        <datum oznaceni="nakup">2020-07-30</datum>
                        <cena mena="CZK">106</cena>
                        <uhrazeno>kredity</uhrazeno>
                    </platba>
                </trasa>
                <dotaznik>
                    <hodnoceni>
                        <celkove>8</celkove>
                        <personal>8</personal>
                        <cistota>8</cistota>
                    </hodnoceni>
                    <komentar>
                        Průměrná cesta, děkuji za dochvilnost.
                    </komentar>
                </dotaznik>
            </jizdenka>
        </jizdenky>
    </uzivatel>
    <uzivatel>
        <osobni_udaje id_uzivatele="1862-1282">
            <jmeno>Andrea</jmeno>
            <prijmeni>Matúšová</prijmeni>
            <datum oznaceni="narozeni">1999-12-15</datum>
            <email>andrea.matusova@gmail.com</email>
            <telefon>+420731256987</telefon>
        </osobni_udaje>
        <jizdenky>
            <jizdenka>
                <trasa id_trasy="10588-39601-08955">
                    <informace>
                        <datum oznaceni="jizdenka">2019-08-04</datum>
                        <odkud>Studénka</odkud>
                        <kam>Pardubice</kam>
                        <vyjezd>13:38:00</vyjezd>
                        <prijezd>15:42:00</prijezd>
                        <trida>business</trida>
                        <sedadlo>
                            <vuz>A</vuz>
                            <cislo>16</cislo>
                        </sedadlo>
                    </informace>
                    <platba>
                        <datum oznaceni="nakup">2019-08-01</datum>
                        <cena mena="CZK">526</cena>
                        <uhrazeno>karta</uhrazeno>
                    </platba>
                </trasa>
                <nakup>
                    <polozky>
                        <polozka danovy_doklad="113238852149">
                            <nazev>Káva espresso</nazev>
                            <cena mena="CZK">39</cena>
                            <uhrazeno>hotovost</uhrazeno>
                        </polozka>
                        <polozka danovy_doklad="108783992145">
                            <nazev>Salát Caesar</nazev>
                            <cena mena="CZK">109</cena>
                            <uhrazeno>hotovost</uhrazeno>
                        </polozka>
                        <polozka danovy_doklad="108793112245">
                            <nazev>Ugova štáva</nazev>
                            <cena mena="CZK">69</cena>
                            <uhrazeno>karta</uhrazeno>
                        </polozka>
                    </polozky>
                </nakup>
                <dotaznik>
                    <hodnoceni>
                        <celkove>10</celkove>
                        <personal>10</personal>
                        <cistota>9</cistota>
                    </hodnoceni>
                    <komentar>Stoprocentní kvalita</komentar>
                </dotaznik>
            </jizdenka>
            <jizdenka>
                <trasa id_trasy="16685-98965-66841">
                    <informace>
                        <datum oznaceni="jizdenka">2020-01-02</datum>
                        <odkud>Praha, hl.n.</odkud>
                        <kam>Ostrava, hl.n.</kam>
                        <vyjezd>12:08:00</vyjezd>
                        <prijezd>18:18:00</prijezd>
                        <trida>premium</trida>
                        <sedadlo>
                            <vuz>E</vuz>
                            <cislo>212</cislo>
                        </sedadlo>
                    </informace>
                    <platba>
                        <datum oznaceni="nakup">2019-12-31</datum>
                        <cena mena="CZK">268</cena>
                        <uhrazeno>karta</uhrazeno>
                    </platba>
                </trasa>
                <nakup>
                    <polozky>
                        <polozka danovy_doklad="108791587752">
                            <nazev>Kofola 0,5l</nazev>
                            <cena mena="CZK">35</cena>
                            <uhrazeno>hotovost</uhrazeno>
                        </polozka>
                    </polozky>
                </nakup>
            </jizdenka>
        </jizdenky>
    </uzivatel>
    <uzivatel>
        <osobni_udaje id_uzivatele="1562-1530">
            <jmeno>Ondřej</jmeno>
            <prijmeni>Šesták</prijmeni>
            <datum oznaceni="narozeni">2000-02-12</datum>
            <email>seso00@vse.cz</email>
            <telefon>+420603185211</telefon>
            <sleva>interrail-1st</sleva>
        </osobni_udaje>
    </uzivatel>
    <uzivatel>
        <osobni_udaje id_uzivatele="1874-1212">
            <jmeno>Petr</jmeno>
            <prijmeni>Jeřábek</prijmeni>
            <datum oznaceni="narozeni">1998-10-09</datum>
            <email>petr.jer@seznam.cz</email>
            <telefon>+420737889411</telefon>
            <sleva>ZTP</sleva>
        </osobni_udaje>
        <jizdenky>
            <jizdenka>
                <trasa id_trasy="88951-15588-20148">
                    <informace>
                        <datum oznaceni="jizdenka">2015-06-15</datum>
                        <odkud>Karviná</odkud>
                        <kam>Přerov</kam>
                        <vyjezd>13:17:00</vyjezd>
                        <prijezd>15:01:00</prijezd>
                        <trida>economy</trida>
                        <sedadlo>
                            <vuz>B</vuz>
                            <cislo>57</cislo>
                        </sedadlo>
                    </informace>
                    <platba>
                        <datum oznaceni="nakup">2015-06-08</datum>
                        <cena mena="CZK">78</cena>
                        <uhrazeno>karta</uhrazeno>
                    </platba>
                </trasa>
